name: Update Schedule

on:
  schedule:
    - cron: '0 0 * * *' # Запуск раз в сутки
  workflow_dispatch: # Возможность ручного запуска

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pandas openpyxl

      - name: Run parser script
        run: python main.py # Замени на имя своего главного скрипта, если оно другое

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update schedule data" || exit 0
          git push

      - name: Send Telegram Notification
        env:
          TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          curl -s -X POST https://api.telegram.org/bot$TOKEN/sendMessage \
            -d chat_id=$CHAT_ID \
            -d text="✅ Расписание успешно обновлено! Новые данные уже загружены в репозиторий."
